# Generated by Django 5.2 on 2025-04-28 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_xp', models.IntegerField(default=0)),
                ('next_xp', models.IntegerField(default=100)),
                ('level', models.IntegerField(default=1)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('finished', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=1)),
                ('userData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userdata')),
            ],
        ),
    ]
